/**
 * Bundle src/main.ts into main.js — the single file Obsidian loads.
 *
 * Node builtins stay external: Obsidian is Electron, so `node:http` and
 * friends resolve at runtime. Bundling them would only bloat the plugin.
 */
import esbuild from "esbuild";
import process from "node:process";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
Vault Gate — https://github.com/rileygramlich/obsidian-gate
This file is generated by esbuild. Edit the TypeScript in src/ instead.
*/
`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    ...builtins,
    ...builtins.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outfile: "main.js",
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
